### ISSUE TITLE
AOL CHAT ROOM

### ISSUE THREAD

**Issue by RedRaptor93** [jendabek/BlenderRenderController#2]
There are some things I did for my now defunct "settings_file" branch that I want to integrate to you project, I already did a pull request which you seem to have missed and developed passed...

I don't want to be annoying or anything, I just want to help where I can. I see you are actively developing your side and a lot of it is stuff I wanted to do anyway.

Another thing, I'm using Visual Studio 2015, Is there a way to open a pull request from it after cloning it to my computer? Or I need to create a repository manually w/ my changes like I did?

**Comment by jendabek** [comment]
Hello, I had to complete some changes that I think were important and I have not found a way to merge your pull request after that, sorry.
I am not going to update it for some time (several days or so...) ... so can you please try to modify the request according to that current version?
I am not very familiar with all those Git tricks, I am happy I was able to checkout BlenderRenderController project from GitHub :)
Maybe this could help you?
https://www.visualstudio.com/en-us/docs/git/pull-requests

I plan to make a video about the program and put it on Youtube, what do you think? It seems like it could be working quite well in the current state.

**Comment by jendabek** [comment]
We could see if there is enough potential in the app and then maybe we should write some changes / features to add and order them by priority...?

**Comment by RedRaptor93** [comment]
I've applied the changes I wanted to the latest commit, I'll check the link and see if I can put a pull request for you to see.

Making a video sounds like a good idea, get the world out there, if you want help creating that let me know. 😉 

Spreading the world within the Blender community (places like  https://blenderartists.org/forum/), then we can see how they like it, what changes they want, etc

**Comment by jendabek** [comment]
Exactly! I am going to continue on my main project now, which is a racing track, modeling in Blender of course. You can have a look, if you are interested in :)
http://www.jankaderabek.com

**Comment by RedRaptor93** [comment]
Ok I THINK I've figured it out, I'll make that push request soon

**Comment by jendabek** [comment]
I added releases of the current version. The "full" one has FFmpeg included.
I have a question - do you think I can add a Donate button and point it to my Paypal, while I would send you and Isti some part of the received amount?
What rules do you suggest for this? I think it would be shame to not use that possibility.

**Comment by RedRaptor93** [comment]
Well if we're speaking donations, we have to come to an understanding with the authors involved

The problem I feel is the project is currently fragmented, between mine, Isti155 and yours. Your fork is a complete rewrite code wise, basically. It would be wierd having your fork, with a donation button and the others, functionally different forks without.

However, if we get everybody on the same page, it'll be all good.

**Comment by jendabek** [comment]
I understand. So what do you suggest at this moment?

**Comment by RedRaptor93** [comment]
First we think should have all parties discuss about how BRC will develop from now on, I feel the wisest choice is to develop w/ on top of your fork, which is way ahead in terms of features. We should discuss that to make sure everyone is on the same page.

**Comment by RedRaptor93** [comment]
Open an Issue on Isti155's project and let's call the authors we can, and tell them about this.

**Comment by jendabek** [comment]
The video, not so fancy but OK I hope:
https://www.youtube.com/watch?v=Kdvq1CzOPfM

**Comment by jendabek** [comment]
Hello, please look at this comment:
http://www.youtube.com/watch?v=xSGIPmQdV6M&google_comment_id=z12henqr1rrgxzbr404cchg4stmxcfyhea4

**Comment by RedRaptor93** [comment]
Nice, I actually watched his series when I first started to editing in Blender

Do you have any plans for when he sends his code?

**Comment by jendabek** [comment]
I think we should think about merging our tools together somehow...? He says he will mention BRC in his video, that could help to gain an interest in it too I hope.
From a different topic - I tried to merge your last pull request but had some issues with duplicated controls declaration.
About the invalid path issue. I appreciate you have found that bug and it should be fixed but I think we should try to avoid any error messages unless it is absolutely needed. This helps to get smooth user-experience when working with the program. I think the better way to fix that bug would be detect that the path is invalid and set it automatically to .blend's folder for example. No message needed and it definitely shouldn't be a reason to not load the .blend. It will also make the code more simple.
What do you think?

Also I suggest to add a topic here with the most important features / fixes we need to implement, do you agree?

**Comment by jendabek** [comment]
About the merging - I will try it tomorrow again and will let you know.

**Comment by RedRaptor93** [comment]
really? I double checked for those duplicated declarations, guess I must have missed some

I did that error message cause It caused an  unhanded exception, and it didn't load the file anyway, so I figured having a error message about path resolution failing was worth it. But your solution sounds better indeed.

Also I am still getting used to your code, as it's completely different, so I wanted to see if I could add something like that w/o breaking it.

**Comment by RedRaptor93** [comment]
UPDATE

fixed the duplicated declarations, pushing it soon

**Comment by jendabek** [comment]
FYI, if you are curious to see how many times our app was downloaded, search for "download_count" here:
https://api.github.com/repos/jendabek/BlenderRenderController/releases
Nothing bombastic so far 😄

**Comment by jendabek** [comment]
I think it would be worth to look at Mono to make our app multiplatform. What do you think? I think it is a must have because the script of Mike Meyers is going to be multiplatform too. So it would be big disadvantage for our tool then.

**Comment by RedRaptor93** [comment]
Yea, I think for the time been we're good feature wise. Going for Mono sounds like the best thing to do right now...

Monday I'll be going back to collage, so I won't have the free time I've been having to do programming stuff, but I'll still try to keep up when possible 😸 

I've been learning about C# a lot, got a couple of courses (intermediate and advanced) for a good price and I'm invested in learning about it. And this little project is what motivated me to do it 👍

**Comment by jendabek** [comment]
Hello guys, I need your PayPal emails to send you your parts of a donation I have received today.
Thanks!

**Comment by RedRaptor93** [comment]
Ok, sent it to your e-mail.

Btw have you seen my logger commit? I think it's pretty good ^^

**Comment by jendabek** [comment]
Hello, after merging your latest pull request, I get lots of errors in the IDE - I think it is related to your Linux override of MainForm that confuses VS?
![2017-03-21_231855](https://cloud.githubusercontent.com/assets/3582231/24173607/f8d4c43a-0e8c-11e7-9e20-4293db8f40ca.jpg)

**Comment by RedRaptor93** [comment]
No... It was single `}` that was out of place

God dammit 😠 

At least its a quick fix, stand by

**Comment by RedRaptor93** [comment]
Update: Done

**Comment by jendabek** [comment]
Haha, thats ok :) No errors now - thanks :)
